consumerSourceDataSets:
  path: Microsoft.AppPlatform/accounts/sharesubscriptions/consumerSourceDataSets
  description: UNKNOWN
  status: ASSESS
  url: Microsoft.AppPlatform/accounts/sharesubscriptions/consumerSourceDataSets
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
datasetmappings:
  path: Microsoft.AppPlatform/accounts/sharesubscriptions/datasetmappings
  description: UNKNOWN
  status: ASSESS
  url: Microsoft.AppPlatform/accounts/sharesubscriptions/datasetmappings
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
triggers:
  path: Microsoft.AppPlatform/accounts/sharesubscriptions/triggers
  description: UNKNOWN
  status: ASSESS
  url: Microsoft.AppPlatform/accounts/sharesubscriptions/triggers
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
