importImage:
  path: Microsoft.AlertsManagement/offerTypes/publishers/offers/plans/configs/importImage
  description: UNKNOWN
  status: ASSESS
  url: Microsoft.AlertsManagement/offerTypes/publishers/offers/plans/configs/importImage
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
