storedProcedures:
  path: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/storedProcedures
  description: UNKNOWN
  status: TRIAL
  url: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/storedProcedures
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
throughputSettings:
  path: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/throughputSettings
  description: UNKNOWN
  status: TRIAL
  url: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/throughputSettings
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
triggers:
  path: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/triggers
  description: UNKNOWN
  status: TRIAL
  url: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/triggers
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
userDefinedFunctions:
  path: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/userDefinedFunctions
  description: UNKNOWN
  status: TRIAL
  url: Microsoft.DBforPostgreSQL/databaseAccounts/sqlDatabases/containers/userDefinedFunctions
  architecture review:
    type: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no architectural notes for this service at this time.
  security review:
    class: UNKNOWN
    status: NOT REVIEWED
    start: NOT STARTED
    end: NOT ENDED
    notes: There are no security notes for this service at this time.
